version: v0.10.1

dsn: ""

serve:
  public:
    base_url: 'https://defcon-ory-challenge.com'

selfservice:
  default_browser_return_url: '/'
  flows:
    error:
      ui_url: https://defcon-ory-challenge.com/error
    login:
      ui_url: https://defcon-ory-challenge.com/login
    registration:
      ui_url: https://defcon-ory-challenge.com/register
      after:
        webauthn:
          hooks:
            - hook: session
  methods:
    password:
      enabled: false
    webauthn:
      enabled: true
      config:
        passwordless: true
        rp:
          display_name: Ory DEF CON CTF
          id: localhost
          origin: https://defcon-ory-challenge.com

courier:
  smtp:
    connection_uri: 'smtp://localhost:25'

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///home/ory/identity.schema.json
