version: v0.10.1

dsn: ""

serve:
  public:
    base_url: 'http://localhost:5050'

selfservice:
  default_browser_return_url: '/'
  flows:
    login:
      ui_url: http://localhost:5050/login
    registration:
        ui_url: http://localhost:5050/register
        after:
          password:
            hooks:
              - hook: session

courier:
  smtp:
    connection_uri: 'smtp://localhost:25'

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///home/ory/identity.schema.json
